### PR TITLE
Update example.py

### PR DESCRIPTION
**Pull request by dedalgr**
Transaction is successful if finish with aft_clean_transaction_poll

### CODE REVIEW

**Comment by dedalgr** [comment]
Transaction is successful if finish with

**Review by zacharytomlinson — APPROVED** [review]

**Comment by well-it-wasnt-me** [comment]
At this point, why not call aft_clean_transaction_poll directly inside aft_in ?

**Comment by dedalgr** [comment]
Do not use aft_clean_transaction_poll in directly inside aft_in because the machine response time is different. A proper use of aft_clean_transaction_poll is to loop it. If it raises an error or returns 'Transfer pending (not complete)' you continue to execute until 'Full transfer successful'. Otherwise, you break the cycle and make the request invalid.

**Comment by well-it-wasnt-me** [comment]
Thank you so much for the clarification !

**Comment by dedalgr** [comment]
It works in 40-50 casinos sas.py is my mod.

my_out = None
for i in range(3):
if my_out == None:
if self.slee_on_down is True:
time.sleep(self.sas_sleep)
try:
self.clear_meter()
my_out = self.meter['out']
# my_out = all_meter = self.sas.send_meters_10_15(True)
except Exception as e:
my_out = None
self.log.error(e, exc_info=True)
else:
break
# self.log.error('get in client_bonus')
if my_out != None:
if bonus_waith_for_in is True and my_out - out >= self.cust_hold_mony:
# time.sleep(4)
self.log.warning('NO CREDIT FOR BONUS')
return 'BREAK'
if self.slee_on_down is True:
time.sleep(self.sas_sleep)
if waith_to_play > time.time():
try:
if kwargs['restricted'] is False:
if self.check_for_game is True:
data = self.sas.AFT_won(mony=mony, amount=1)
else:
data = self.sas.AFT_won(mony=mony, amount=1, games=1)
else:
data = self.sas.AFT_in(mony=mony, amount=2)
except Exception as e:
data = None
self.log.warning(e, exc_info=True)
else:
return False
if data == 'NoGame':
# time.sleep(4)
self.log.warning('NO GAME SELECTED: %s', data)
return False
data = None
while request_time > time.time():

if data == None or data is False:
if self.slee_on_down is True:
time.sleep(self.sas_sleep)
try:
data = self.clean_transaction_poll()
except sas.BadCRC as e:
data = None
self.log.info(e, exc_info=True)
except sas.BadTransactionID as e:
data = None
self.log.error(e, exc_info=True)
except Exception as e:
data = None
self.log.error(e, exc_info=True)
else:
if data['Transfer status'] == 'Full transfer successful':
self.old_in = self.meter['in']
self.log.info('client_bonus: sas response %s', data)
if kwargs['block_out']:
self.no_out_befor(**kwargs['block_out'])
self.bonus_old_in = self.meter['in']
if kwargs['hold_bonus']:
self.player_hold(**kwargs['hold_bonus'])
return True
elif data['Transfer status'] == 'Transfer pending (not complete)':
if self.emg_type == 7 or self.emg_type == 8:
self.bonus_clear_transaction_pool = True
self.old_in = self.meter['in']
self.log.info('client_bonus: sas response %s', data)
if kwargs['block_out']:
self.no_out_befor(**kwargs['block_out'])
if kwargs['hold_bonus']:
self.player_hold(**kwargs['hold_bonus'])
return True
data = None
# elif data['Transfer status'] == 'Gaming machine unable to perform
transfers at this time (door open, tilt, disabled, cashout in progress,
etc.)':
# if self.mem_server.get('MAKE_IN_OUT'):
# self.mem_server.set('MAKE_IN_OUT', False)
# self.sas.remote_handpay_reset()
# return False

else:
self.log.error('client_bonus: sas response %s', data)
return False
self.log.warning('client_bonus time out: sas response %s', data)
# if self.clean_aft_tranzaction is True:
return False

На нд, 28.01.2024 г. в 12:08 Antonio ***@***.***> написа:

**Comment by dedalgr** [comment]
My system is very large and complex. I have SMIB with rfid client module
cashless and 4" touch screen. Jackpot server, central information server,
cashier program, croupier and overall management of all cash flow in
casino. I also have my own SAS protocol, but the modified one works better
than mine.

На нд, 28.01.2024 г. в 15:54 Григор ***@***.***> написа:

**Pull request merged**
