### PR TITLE
Quick revision in sas.py

### PR DESCRIPTION
**Pull request by zacharytomlinson**
Add example.py to gitignore and ran static code analysis (flake8) on sas.py. Commented out EFT functions that had errors while we evaluate whether they are needed or not.

### CODE REVIEW

**Review by well-it-wasnt-me — CHANGES_REQUESTED** [review]
At this point, does kwargs has still meaning to exist ?

**Comment by zacharytomlinson** [comment]
Not at all since we are explicitly stating arguments. I can remove those.

**Comment by zacharytomlinson** [comment]
I think flake8 added that in there.

**Comment by well-it-wasnt-me** [comment]
> Not at all since we are explicitly stating arguments. I can remove those.  

Please proceed then so I approve and merge this request

**Comment by zacharytomlinson** [comment]
@well-it-wasnt-me should be done

**Review by well-it-wasnt-me — APPROVED** [review]

**Pull request merged**
